// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCo-z_EssP9W6iQyKzm9RVcqCooJStqjG0',
    appId: '1:219146953246:web:be51374759bd587b6f840f',
    messagingSenderId: '219146953246',
    projectId: 'flutter-c6ed9',
    authDomain: 'flutter-c6ed9.firebaseapp.com',
    storageBucket: 'flutter-c6ed9.appspot.com',
    measurementId: 'G-NYW200FDMG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYSt352TPnUPUwkhz3JsHRtGtM7_cLGxU',
    appId: '1:219146953246:android:595eb507c37f95ee6f840f',
    messagingSenderId: '219146953246',
    projectId: 'flutter-c6ed9',
    storageBucket: 'flutter-c6ed9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPideB2oqspH_cpxL5kkHzVyfkVWBTesc',
    appId: '1:219146953246:ios:5b627c54dfc37c236f840f',
    messagingSenderId: '219146953246',
    projectId: 'flutter-c6ed9',
    storageBucket: 'flutter-c6ed9.appspot.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPideB2oqspH_cpxL5kkHzVyfkVWBTesc',
    appId: '1:219146953246:ios:5b627c54dfc37c236f840f',
    messagingSenderId: '219146953246',
    projectId: 'flutter-c6ed9',
    storageBucket: 'flutter-c6ed9.appspot.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCo-z_EssP9W6iQyKzm9RVcqCooJStqjG0',
    appId: '1:219146953246:web:92d6875314c3974c6f840f',
    messagingSenderId: '219146953246',
    projectId: 'flutter-c6ed9',
    authDomain: 'flutter-c6ed9.firebaseapp.com',
    storageBucket: 'flutter-c6ed9.appspot.com',
    measurementId: 'G-JEQ849DZ6Q',
  );

}